version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" # Port for SQS

##docker-compose up --build
##aws sqs create-queue --queue-name transactionlog-approved-local --endpoint-url=http://localhost:4566
##aws --endpoint-url=http://localhost:4566 sqs list-queues
##aws sqs send-message --queue-url http://localhost:4566/000000000000/transactionlog-approved-local --message-body='Hello, world 3!' --endpoint-url=http://localhost:4566
##aws sqs receive-message --queue-url http://localhost:4566/000000000000/transactionlog-approved-local --endpoint-url=http://localhost:4566